[theme]
base = "light"

# Color primario (acento)
primaryColor = "#B38E2D"   # Dorado UNAM refinado

# Fondo general (muy suave, no blanco puro)
backgroundColor = "#EEF2F7"

# Fondo de tarjetas / widgets
secondaryBackgroundColor = "#FFFFFF"

# Texto principal
textColor = "#1E293B"

# Tipografía
font = "sans serif"